### ISSUE TITLE
involve PING in the process earlier

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/admin#75] opened 2019-07-17 22:49 UTC
Talking to folks participating in PING, we are wondering if it would be possible for us Chairs to notify PING when we kick off incubations? 

Basically, we could add this to the initial transition steps:
https://github.com/WICG/admin/wiki/Process-to-transfer-a-repo

 cc @snyderp

**Comment by pes10k** [comment] 2019-07-18 22:02
Thanks @marcoscaceres!

It would be great to notify all the horizontal review groups when new incubations start, just so relevant parties can touch bases and work with chairs as early in the process as possible (to keep things as collaborative as possible).

**Comment by marcoscaceres** [comment] 2019-07-30 11:28
Quick investigation: the way to do this would be to create a webhook that pings an end point that sends emails to various working groups when a repository is created. 

@plehegar... I wonder if the end-point could live on the W3C side. We'd need something like "Nodemailer" running on the w3c side... or something similar.

**Comment by plehegar** [comment] 2019-07-30 12:52
Why not sending an email to public-review-announce@w3.org ?

**Comment by marcoscaceres** [comment] 2019-07-30 23:54
I didn’t know that was a thing:) if that list reaches the right people, then sure!

**Comment by marcoscaceres** [comment] 2019-07-31 09:35
Ok, I guess this happens rarely enough that we should just do it manually.

**Comment by marcoscaceres** [comment] 2019-07-31 09:40
@WICG/chairs I'll add a step to email "public-review-announce@w3.org" when a new repo goes up. @snyderp or @plehegar, please confirm ping is already getting notified there.

**Comment by marcoscaceres** [comment] 2019-07-31 09:41
Ok, done:
https://github.com/WICG/admin/wiki/Process-to-transfer-a-repo

**Comment by marcoscaceres** [comment] 2019-07-31 09:42
Closing. If this needs more work let me know and I can reopen.

**Comment by yoavweiss** [comment] 2019-07-31 10:13
When a new repo goes up might be a bit too early for such a review (there may be nothing much to review beyond an early phase explainer).

It might be worthwhile to think how horizontal reviews tie in to the TAG review process. Maybe PING and other groups can subscribe to that repo?

**Comment by plehegar** [comment] 2019-07-31 14:46
in my experience, you need a multi-channel of communications to ensure that folks will see things. I'll suggest the idea that they should monitor the TAG repo as well.

**Comment by plehegar** [comment] 2019-07-31 14:48
also, note that @dontcallmedom has a tool that can notify on GH repo creation/deletion. See https://github.com/w3c/github-notify-ml-config/blob/master/mls.json#L907 for an example.

**Comment by marcoscaceres** [comment] 2019-07-31 14:57
@snyderp, you want to be involved super early, right?

**Comment by pes10k** [comment] 2019-07-31 18:48
@marcoscaceres yes I think keeping the HR folks in the loop as early as possible is important.

For context, this is related to the conversation going on in the W3C process group: https://github.com/w3c/w3process/issues/130#issuecomment-514792045

**Comment by travisleithead** [comment] 2020-05-14 22:09
Hi @pes10k! 

Just came across this old issue. Not sure if we need any more process other than what is currently working so far. If the status quo is meeting your needs, I'd like to propose closing this issue. Would love to hear your thoughts.

**Comment by pes10k** [comment] 2020-05-15 03:14
@travisleithead i think this would be great, but I'm not sure I understand the resolution.  How should HR groups get notified of entering / exiting incubations?

**Comment by marcoscaceres** [comment] 2020-05-15 05:56
> How should HR groups get notified of entering / exiting incubations?

For, additions to the community group, please subscribe to changes to our [tracking spreadsheet](https://docs.google.com/spreadsheets/d/1K2EtkvKXMDk_h2goR34uMIWmw1LfPhIi-QAJHcQBP_4/edit?usp=sharing) via a notification rule (in the toolbar menu of the spreadsheet, search for "notifications"). This is also what we Chairs use to notify each other of new incubations. 

For exiting, we can amend the the graduation template to have a "ping PING" requirement, in addition to getting permission from a working group to accept the work.

**Comment by pes10k** [comment] 2020-05-19 23:49
> For, additions to the community group, please subscribe to changes to our tracking spreadsheet via a notification rule (in the toolbar menu of the spreadsheet, search for "notifications"). This is also what we Chairs use to notify each other of new incubations.

Sounds good, i'll sign up for this.  Thanks!  If possible though, it'd be ideal to have a way to notify other HR groups, and not just individual chairs.  It seems the only way i can get notifications is through / to the google account im logged in as, so I couldn't, say, sign up the W3C PING / PrivacyCG chairs lists.  Do you know of some way to do this?

> For exiting, we can amend the the graduation template to have a "ping PING" requirement, in addition to getting permission from a working group to accept the work.

Yes, i think those would both be terrific changes.  Thank you @marcoscaceres !

**Comment by marcoscaceres** [comment] 2020-05-20 06:20
> Do you know of some way to do this?

I don’t... i guess maybe using some Gmail filter rule could work... “if from x or subject starts with ... , forward it to y”?

**Comment by pes10k** [comment] 2020-05-20 18:19
Sounds good, I can see if I can make something work like that.   It'd be ideal though if there was some non-google-account (or bounced from a google account) tied way for other W3C members to stay up to date with CG activities, especially other HR groups. Could this be tied into GH repos somehow?

**Comment by plehegar** [comment] 2020-05-20 21:58
@pes10k would generating an html file out of the spreadsheet and pushing it on a daily basis into a WCIG repo help? You'd get something like https://w3c.github.io/gargantua/tmp/wcig-tracking.html

**Comment by pes10k** [comment] 2020-05-21 17:17
@plehegar I appreciate the offer, but I dont think that would help.  I think just being PING'ed when a feature / project / repo goes to TAG review, and if possible when its created would be great.  I think probably per update notifications would be more info than would be useful

**Comment by dontcallmedom** [comment] 2020-05-26 13:21
@pes10k we could use https://github.com/dontcallmedom/github-notify-ml/ to send an email whenever a repo is created in or transfered to WICG - would that help?

**Comment by pes10k** [comment] 2020-05-26 19:21
I think that would be terrific! As long there is someway for other HRs to follow along that doesn't require a google (or any other non-w3c) account, i think would be fantastic :)

**Comment by dontcallmedom** [comment] 2020-05-27 13:36
@pes10k everything is now ready for sending notifications on WICG repo creation or transfer - the only thing I need at this point is a target email address - any suggestion?

**Comment by pes10k** [comment] 2020-05-27 13:55
Hi @dontcallmedom, I dont have a specific email address in mind beyond my own, but i think its important for an member (W3C HR group or otherwise) to be able to follow new proposed / incubated specs as they work through the process.  Is there anyway for people to generally be able to sign up for notifications?

**Comment by dontcallmedom** [comment] 2020-05-27 13:57
@pes10k is there a mailing list that HR people already watch for similar type of information? that would be natural candidate.

@plehegar any suggestion on your end?

**Comment by pes10k** [comment] 2020-05-28 04:27
@dontcallmedom I am not aware of anything like that, unfortunately

**Comment by dontcallmedom** [comment] 2020-05-28 08:46
@pes10k OK for now, I've just made [your email address the recipient of the notifications](https://github.com/w3c/github-notify-ml-config/blob/master/mls.json#L992) - anyone can add themselves to the recipient list by submitting a pull request to update the said configuration file for now.

I think having a mailing list as a recipient is the better longer term approach - I defer to @plehegar to figure out what list to use.

I have tested this, but it would be best to check it really works in practice - so @marcoscaceres it would be great if you could think of checking with @pes10k next time a WICG repo is created and next time a repo is transferred to make sure he indeed got the notification.

**Comment by plehegar** [comment] 2020-05-28 12:59
@dontcallmedom public-review-announce@w3.org would be a good one. We are receving notifications for first public working drafts, calls for wide reviews, and Candidate Recommendations.

**Comment by dontcallmedom** [comment] 2020-05-28 14:29
@pes10k would you be willing to subscribe to public-review-announce@w3.org to receive the WICG repo notifications?

**Comment by pes10k** [comment] 2020-05-28 16:32
Sure, I already subscribe to that; i think that'd be great if its not too much noise for the other folks on public-review-announce@w3.org

**Comment by dontcallmedom** [comment] 2020-05-29 13:41
public-review-announce should be pinged now - I'm guessing that issue can be closed once we confirm this is working as expected

**Comment by dontcallmedom** [comment] 2020-06-04 06:58
The list was notified of a transfer:
  https://lists.w3.org/Archives/Public/public-review-announce/2020Jun/0000.html
which confirms the notifications work as expected; I believe the issue can be closed now

**Comment by pes10k** [comment] 2020-06-04 15:50
Thanks very much @dontcallmedom @plehegar and @marcoscaceres , looks great :)

**Comment by cwilso** [comment] 2020-06-04 16:11
Cool, seems like we can close this then.

**Closed as completed by cwilso** 2020-06-04 16:11 UTC

**Comment by pes10k** [comment] 2020-06-10 14:49
Hi @dontcallmedom , just wanted to check; i see updates from the google doc, but not on public-review-announce@w3.org. I can't tell _what_ has changed in the google doc, so I dont know if this is bug or intended.  Just wanted to check that information hasn't been missed.

**Comment by dontcallmedom** [comment] 2020-06-10 15:10
@pes10k I don't know what changes were made to the spreadsheet, so I don't know if updates were missed - @marcoscaceres can you help?

**Comment by travisleithead** [comment] 2020-06-11 05:24
Not sure if this option is available (I have edit permission, so not sure if this translates), but on Windows, 'Ctrl+Shift+Alt+H' opens the sheet's version history--and enables easy visualization of the changes that have been made. Clicking the link just to the right of the `Help` menu, title something like "Last Edit..." also opens the version history.

**Comment by dontcallmedom** [comment] 2020-06-11 06:24
I personally don't have the sufficient privileges to access the document history

**Comment by plehegar** [comment] 2020-06-11 12:33
Would be good to see if everyone can access the history indeed.

The spreadsheet is saved into https://github.com/WICG/wicg.github.io (as JSON and HTML). If a change on the spreadsheet happens, we could notify the list but the change may not be about a review request so we would be spamming public-review-announce imho. You could check the [commit history of the JSON](https://github.com/WICG/wicg.github.io/commits/master/tracking.json), easier to read than the HTML, even if not as ideal as accessing the history.

**Comment by pes10k** [comment] 2020-06-19 17:09
@plehegar I'm still seeing "the google doc has been updated" messages, without corresponding emails to public-review-announce@w3.org explaining what the changes were.  My understanding from https://github.com/WICG/admin/issues/75#issuecomment-642059919 is that the mailing list would be notified when there were changes here, since the gdoc doesn't have public history or information about what was changed.

Are things working as intended? Is the most recent gdoc updated one that wasn't intended to be emailed out too?

**Comment by travisleithead** [comment] 2020-06-19 19:06
The most recent change was the addition of a comment under the column "next steps" for a particular incubation. Naturally, this doesn't merit an announce on the list. I think it would be a terrible idea to send all doc changes to that list (or we'd want a different doc with a minimal amount of tracking data to tie the announcements to).

Bottom line, things are still working as intended.

**Comment by pes10k** [comment] 2020-06-19 19:12
Okie dokie. Just wanted to double check since I’ve seen lots of doc notices but no announcements. Thank you for checking / confirming that things are working correctly:)
