### ISSUE TITLE
Provide a template repository

### ISSUE THREAD

**Issue by jyasskin** [WICG/admin#79] opened 2019-09-14 17:39 UTC
https://wicg.github.io/admin/charter.html#contrib describes some requirements on repositories added to the WICG, so it'd be nice to be able to copy a template repository that already has those files.

https://help.github.com/en/articles/creating-a-template-repository gives instructions.

**Comment by marcoscaceres** [comment] 2019-09-16 02:46
The starter kit is supposed to do this... but we should actually document that :) 

https://github.com/WICG/starter-kit

**Comment by jyasskin** [comment] 2019-09-16 02:56
Oh, right. And pin that repository to your [org](https://github.com/WICG) along with this `admin` repo. :)

**Comment by marcoscaceres** [comment] 2019-09-16 03:39
Great suggestion. Pinned!

**Comment by pes10k** [comment] 2020-02-10 20:55
Hi all.  I'm not sure if this is the correct place, but as per https://github.com/w3c/tr-design/pull/177, i think the WICG repos need to be updated to use the new template.

**Comment by jyasskin** [comment] 2020-02-10 21:35
@snyderp I'd suggest a new issue in general. If w3c/tr-design#186 changes the W3C-ED stylesheet, most specs here should just pick it up with a reload. If any don't, they might need to rebuild with an updated bikeshed or respec, or they might need some investigation.

**Comment by pes10k** [comment] 2020-02-10 23:28
@jyasskin if i understand correctly, https://github.com/w3c/tr-design/issues/186 will solve?  And if not, new issue?

**Comment by marcoscaceres** [comment] 2020-02-10 23:34
Yes, should solve for w3c/tr-design#186. No idea what's happened there. I'm not seeing the UNOFFICIAL watermark on ED drafts - so that's already weird.

**Comment by travisleithead** [comment] 2020-05-14 22:15
Looks like we've wandered over into a duplicate of issue #90. :) Let's continue any discussion on that topic over there.

**Closed as completed by travisleithead** 2020-05-14 22:15 UTC
